config/routes.rb
Facee::Application.routes.draw do
  
  namespace :api do
    namespace :user do 
      %w(authorize list info user_info follow friend friends followers following upload_avatar edit user_fb_info).each do |action|
        match action , :via=>[:get,:post]
      end
    end
    namespace :comment do 
      %w(list post delete).each do |action|
        match action , :via=>[:get,:post]
      end
    end
    namespace :pictures do 
      %w(pay set_attr list info delete post like strim like_list).each do |action|
        match action , :via=>[:get,:post]
      end
    end
  end



  get 'admin',  to: "admin#index" 
  get 'logout', to: "admin#exit"
  namespace :admin do
    post "login_admin"
    resources :users
    resources :photos
    resources :articles
     get "activity", to: "activity#index"
  end


  root :to => 'main#index'
  get "item/:id", to:  'main#item'
  match "doc" , to:  'main#index_old'
  match '*a',   :to => 'api/api#routing_error'



end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
	before_filter :require_login
	def index
		per_page = 10
		type = params[:type] || 1
		@characters = Description.where(:item_type=>type).order_by("item_period ASC").paginate(:per_page=>per_page,:page => params[:page])
	end

	def new
		get_periods
		@article = Description.with(database: "facee_production").new
	end

	def edit
		get_periods
		@article = Description.with(database: "facee_production").find(params[:id].to_i)
	end

	def create
		params[:article][:item_type].gsub!("t_",'')
		@article = Description.with(database: "facee_production").new(params[:article])
		@article.save
		redirect_to admin_articles_path
	end
	def update
		params[:article][:item_type].gsub!("t_",'')
		id = params[:article].delete(:id)
		@article = Description.with(database: "facee_production").find(id.to_i)
		@article.update_attributes params[:article]
		redirect_to admin_articles_path
	end

	private

	def get_periods
		@periods = []
		 Description.with(database: "facee_production").generated_dates.size.times do |g| 
			first = [Description.with(database: "facee_production").generated_dates[g].first.day, I18n.t("date.month_names")[Description.generated_dates[g].first.month] ].join(" ")
			last  = [Description.with(database: "facee_production").generated_dates[g].last.day, I18n.t("date.month_names")[Description.generated_dates[g].last.month] ].join(" ")
			@periods << [[ first, last ].join(" do ") , g]
		end
	end
end

app/views/admin/articles/_form.html.haml
.span9.with-sidebar
  - url =  params[:action] =~ /new/ ? admin_articles_path : "/admin/articles/#{@article.id}"  
  .container
    = form_for @article , :as=>:article ,:url => url  ,:html=>{:class=>"new_user_form inline-input"} do |f|
      = f.hidden_field :id
      .span12.field-box
        %label Тип
        = f.select :item_type , options_for_select(t("api.desc_types").invert,@article.item_type.nil? ? "t_1" : "t_#{@article.item_type}") ,{} ,:class=>"span9" , :required=>true
      .span12.field-box
        %label Период
        = f.select :item_period , options_for_select(@periods,@article.item_period.nil? ? 0 : @article.item_period) ,{} ,:class=>"span9" , :required=>true
      - %w(ru en ua).each do |lang|
        .span12.field-box
          %label #{t("admin.articles.desc")} #{lang}
          = f.text_field "body_#{lang}", :class=>"span9" , :required=>true 
      .span11.field-box.actions
        = f.submit t("admin.articles.save"), :class=>"btn-glow primary"

app/views/admin/articles/edit.html.haml
#tabs-wrapper
  .row-fluid
    %a.span2.tab.active{:href=>"/admin/articles"}
      = t("admin.articles.list")
    %a.span2.tab.active{:href=>"/admin/articles/new"}
      = t("admin.articles.add")
    %a.span2.tab.active{:href=>"#"}
      = t("admin.articles.edit")
#pad-wrapper.new-user
  .row-fluid.header
    %h3
  .row-fluid.form-wrapper
    = render 'form'

app/views/admin/articles/index.html.haml
#tabs-wrapper
  .row-fluid
    %a.span2.tab.active{:href=>"/admin/articles/new"}
      = t("admin.articles.add")
    - t("api.desc_types").each do |tf|
      %a.span2.tab{:href=>"/admin/articles/?type=#{tf.first.to_s.gsub('t_','')}"}
        = tf.last


#pad-wrapper.users-list   
  .row-fluid.table{:"data-auto-controller"=>"AdminUsersController"}
    %table.table.table-hover
      %thead
        %tr
          %th.span2.sortable
            Тип      
          %th.span2.sortable
            %span.line
            = t("admin.articles.date") 
          %th.span2.sortable
            %span.line
            = t("admin.articles.desc") 
      %tbody
        - @characters.each_with_index do |item,i|
          - first = [Description.generated_dates[item.item_period].first.day, I18n.t("date.month_names")[Description.generated_dates[item.item_period].first.month] ].join(" ")
          - last  = [Description.generated_dates[item.item_period].last.day, I18n.t("date.month_names")[Description.generated_dates[item.item_period].last.month] ].join(" ")
          %tr{:class=>("active" if i == 0)}
            %td=t("api.desc_types.t_#{item.item_type}")
            %td=link_to [ first, last ].join(" do ") , edit_admin_article_path(item._id) , :class=>"name"
            %td=item.body


  .pagination.pull-right 
    = will_paginate @characters         

app/views/admin/articles/new.html.haml
#tabs-wrapper
  .row-fluid
    %a.span2.tab.active{:href=>"/admin/articles"}
      = t("admin.articles.list")
    %a.span2.tab.active{:href=>"/admin/articles/new"}
      = t("admin.articles.add")
    %a.span2.tab.active{:href=>"#"}
      = t("admin.articles.edit")
#pad-wrapper.new-user
  .row-fluid.header
    %h3
  .row-fluid.form-wrapper
    = render 'form'