config/routes.rb
Facee::Application.routes.draw do
  
  namespace :api do
    namespace :user do 
      %w(authorize list info user_info follow friend friends followers following upload_avatar edit user_fb_info).each do |action|
        match action , :via=>[:get,:post]
      end
    end
    namespace :comment do 
      %w(list post delete).each do |action|
        match action , :via=>[:get,:post]
      end
    end
    namespace :pictures do 
      %w(pay set_attr list info delete post like strim like_list).each do |action|
        match action , :via=>[:get,:post]
      end
    end
  end



  get 'admin',  to: "admin#index" 
  get 'logout', to: "admin#exit"
  namespace :admin do
    post "login_admin"
    resources :users
    resources :photos
    resources :articles
     get "activity", to: "activity#index"
  end


  root :to => 'main#index'
  get "item/:id", to:  'main#item'
  match "doc" , to:  'main#index_old'
  match '*a',   :to => 'api/api#routing_error'



end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_and_belongs_to_many :roles

  def modules
  	modules = []
  	self.roles.each do |role|
  		modules << role.admin_modules 
  	end
  	modules.flatten
  end

  def is_admin?
    self.roles.include?(Role.find_by_role_type(:admin))
  end

  def has_access?
  	self.active > 0
  end

  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
	before_filter :require_login
	def index
		per_page = 10
		sort = params[:sort] || :id
		@dir = params[:dir] == 'DESC' ? 'ASC' : 'DESC'
		@users = AppUser.order_by("#{sort} #{@dir}").paginate(:per_page=>per_page,:page => params[:page])
	end

	def new
		@user  = User.new
		@roles = Role.all.map{|role| [role.name,role.id]}
		@pass  = SecureRandom.hex(10)
	end

	def edit
		@user = AppUser.find(params[:id].to_i)
	end

	def update
		user = AppUser.find(params[:id].to_i)
		user.update_attributes(params[:app_user])
		redirect_to admin_users_path
	end

end

app/views/admin/users/_user_form.html.haml
.span9.with-sidebar
  - url =  params[:action] =~ /new/ ? admin_users_path : admin_user_path(@user)
  .container
    = form_for @user ,:url => url  ,:html=>{:class=>"new_user_form inline-input"} do |f|
      = f.hidden_field :id
      .span12.field-box
        %label=t("admin.users.active")    
        = f.select :active , options_for_select([[t("admin.users.active_1"),1],[t("admin.users.active_0"),0]], @user.active) ,{} ,:class=>"span9" , :required=>true
      .span12.field-box
        %label=t("admin.users.first_name")    
        = f.text_field :name , :class=>"span9" , :required=>true
      .span11.field-box.actions
        = f.submit t("admin.users.#{params[:action]}"), :class=>"btn-glow primary"

app/views/admin/users/edit.html.haml
#tabs-wrapper
  .row-fluid
    %a.span2.tab{:href=>"/admin/users"}
      = t("admin.users.list")
    %a.span2.tab.active{:href=>"#"}
      = t("admin.users.add_edit")
#pad-wrapper.new-user
  .row-fluid.header
    %h3= t("admin.users.add_edit")
  .row-fluid.form-wrapper
    = render 'user_form'

app/views/admin/users/index.html.haml
#tabs-wrapper
  .row-fluid
    %a.span2.tab.active{:href=>"/admin/users"}
      = t("admin.users.list")
    %a.span2.tab{:href=>"#"}
      = t("admin.users.add_edit")


#pad-wrapper.users-list   
  .row-fluid.table{:"data-auto-controller"=>"AdminUsersController"}
    %table.table.table-hover
      %thead
        %tr
          %th.span2.sortable
            = form_tag admin_users_path, :method=>:get do
              = hidden_field_tag :sort , "id"
              = hidden_field_tag :dir , @dir
              = t("admin.users.name")    
          %th.span2.sortable
            %span.line
            = form_tag admin_users_path, :method=>:get do
              = hidden_field_tag :sort , "created_at"
              = hidden_field_tag :dir , @dir
              = t("admin.users.created") 
          %th.span2.sortable
            %span.line
            = form_tag admin_users_path, :method=>:get do
              = hidden_field_tag :sort , "last_activity"
              = hidden_field_tag :dir , @dir
              = t("admin.users.last_activity") 
          %th.span2.sortable
            %span.line
              = t("admin.users.penalties") 
      %tbody
        - @users.each_with_index do |user,i|
          %tr{:class=>("active" if i == 0)}
            %td=user.id
            %td=l(user.created_at.to_date,:format=>:long)
            %td=(user.last_activity.nil? ? "" : l(user.last_activity.to_datetime,:format=>:long))
            %td=user.photos.count
  .pagination.pull-right 
    = will_paginate @users         