config/routes.rb
Facee::Application.routes.draw do
  
  namespace :api do
    namespace :user do 
      %w(authorize list info user_info follow friend friends followers following upload_avatar edit user_fb_info).each do |action|
        match action , :via=>[:get,:post]
      end
    end
    namespace :comment do 
      %w(list post delete).each do |action|
        match action , :via=>[:get,:post]
      end
    end
    namespace :pictures do 
      %w(pay set_attr list info delete post like strim like_list).each do |action|
        match action , :via=>[:get,:post]
      end
    end
  end



  get 'admin',  to: "admin#index" 
  get 'logout', to: "admin#exit"
  namespace :admin do
    post "login_admin"
    resources :users
    resources :photos
    resources :articles
     get "activity", to: "activity#index"
  end


  root :to => 'main#index'
  get "item/:id", to:  'main#item'
  match "doc" , to:  'main#index_old'
  match '*a',   :to => 'api/api#routing_error'



end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Facee Admin"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "admin", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-inverse{:style=>"margin-bottom:0"}
      %nav.navbar-inner
        %a.brand{:href=>"#"}
          = image_tag "logo_ad.png"
        %ul.nav.pull-right
          %li#fat-menu.dropdown
            %a.logout{:href=>"/logout"}
              %span.navbar_icon
        .container
    .hidden-phone#sidebar-nav
      %ul#dashboard-menu
        %li{:class=>("active" if (params[:controller] == "admin"))}
          - if (params[:controller] == "admin")
            .pointer
              .arrow
              .arrow_border
          %a.tab2{:href=>"/admin"}
            %i{:class=>"sidebar-home"}
            %span Главная
        - current_user.modules.each do |modul|
          %li{:class=>("active" if (params[:controller] =~ /#{modul.action}/))}
            - if (params[:controller] =~ /#{modul.action}/)
              .pointer
                .arrow
                .arrow_border
            %a.tab2{:href=>"/admin/#{modul.action}"}
              %i{:class=>modul.ico_cls}
              %span=modul.name
    .content{:role => "main"}
      .container-fluid
        = yield
        

app/views/layouts/admin_login.html.haml
!!!
%html.login-bg
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Facee Admin"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "admin", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    .row-fluid.login-wrapper
      = image_tag "logo-white.png" , :class=>"logo"
      .span4.box
        = form_tag admin_login_admin_path, :remote=>true, :"data-auto-controller"=>"AdminLoginController"  do 
          .content-wrap
            %h6=t("user.enter")
            = text_field :user,:email , :class=>"span12", :required=>true, :type=>"email"
            = text_field :user,:password , :class=>"span12", :required=>true, :type=>"password"
            = submit_tag t("user.enter_submit"), :class=>"submit btn-glow primary login"

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Phiz
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    :javascript
      $(document).ready(function(){
        $(".ac_cord").each(function(){
          $(this).click(function(){
            if ($(this).hasClass("des")){
              $(this).next().slideDown(300);
              $(this).toggleClass("des");
            }
            else {
              $(this).toggleClass("des");
              $(this).next().slideUp(300);
            }
          return false;
          });
        });
        
      });
    - @meta.each_pair do |k,v|
      %meta{:property => k,:content=>v }
    %body
      .page
        .header
          .wrapper
            %ul.nav_menu
              %li
                = link_to t("all.home"),"/"
              %li
                %a{:href => ""} Как єто работает?
              %li
                %a{:href => ""} Характеристики
              %li
                %a{:href => ""} Контакты
            = link_to "","/" ,:class=>"logo"
        = yield
        .clear
        #empty
        .footer
          .wrapper
            .copy=t("all.copy")
            %ul.fut_soc
              %li
                %a.f_b{:href => ""}
              %li
                %a.v_k{:href => ""}

app/views/layouts/application_old.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Facee API"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body#wrapper
    = yield